#pragma once
#include "Resource.h"
#include <map>
#include <iostream>
#define RESOURCE_MAP_ELEMENT(type, cost) RESOURCE_MAP[sc2::UNIT_TYPEID::type] = Resource(sc2::UNIT_TYPEID::type,#type, cost); 

using namespace std;
typedef map<sc2::UNIT_TYPEID, int>	ResourceMap;

map<sc2::UNIT_TYPEID,Resource> RESOURCE_MAP;


void InitResources()
{
	// Setup here a map containing all resources with their name and cost
	RESOURCE_MAP_ELEMENT(PROTOSS_PROBE, 50.0);
	RESOURCE_MAP_ELEMENT(PROTOSS_GATEWAY, 150.0);
	RESOURCE_MAP_ELEMENT(PROTOSS_ZEALOT, 100.0);
	RESOURCE_MAP_ELEMENT(PROTOSS_STALKER, 200.0);
	RESOURCE_MAP_ELEMENT(PROTOSS_CYBERNETICSCORE, 150.0);
	RESOURCE_MAP_ELEMENT(PROTOSS_PYLON, 100.0);
	RESOURCE_MAP_ELEMENT(PROTOSS_ASSIMILATOR, 100.0);
	RESOURCE_MAP_ELEMENT(PROTOSS_NEXUS, 400.0);
	RESOURCE_MAP_ELEMENT(PROTOSS_STARGATE, 350.0);
	RESOURCE_MAP_ELEMENT(PROTOSS_CARRIER, 500.0);
	RESOURCE_MAP_ELEMENT(PROTOSS_DARKTEMPLAR, 250.0);
	RESOURCE_MAP_ELEMENT(PROTOSS_FLEETBEACON, 450.0);
}

