#pragma once
#include "Resource.h"
#include <map>
#include <iostream>
#define RESOURCE_MAP_ELEMENT(type, cost) RESOURCE_MAP[RESOURCES::type] = Resource(RESOURCES::type,#type, cost); 

using namespace std;
typedef map<RESOURCES, int>	ResourceMap;

map<RESOURCES,Resource> RESOURCE_MAP;


void InitResources()
{
	// Setup here a map containing all resources with their name and cost
	RESOURCE_MAP_ELEMENT(MINERALS, 1.0);
	RESOURCE_MAP_ELEMENT(PROBE, 50.0);
	RESOURCE_MAP_ELEMENT(GATEWAY, 150.0);
	RESOURCE_MAP_ELEMENT(ZEALOT, 100.0);
	RESOURCE_MAP_ELEMENT(STALKER, 200.0);
	RESOURCE_MAP_ELEMENT(CYBERNETICS, 150.0);
	RESOURCE_MAP_ELEMENT(PYLON, 100.0);
	RESOURCE_MAP_ELEMENT(ASSIMILATOR, 100.0);
	RESOURCE_MAP_ELEMENT(GAS, 1.0);
	RESOURCE_MAP_ELEMENT(NEXUS, 400.0);
	RESOURCE_MAP_ELEMENT(STARGATE, 350.0);
	RESOURCE_MAP_ELEMENT(CARRIER, 500.0);
	RESOURCE_MAP_ELEMENT(DARKTEMPLAR, 250.0);
	RESOURCE_MAP_ELEMENT(FLEETBEACON, 450.0);
}

